Repository WildCodeSchool/orleans-0219-php-gtb, pull requests merged in 2019-06, with the labels that each got.

#20 ajout du fichier _footer.html.twig, ajout du css du footer dans le fi…
  assets/scss/app.scss
  templates/_footer.html.twig
  templates/home/index.html.twig
Labels: Reviewed by PO

#34 Sprint01_US62_Accueil_LeClub
  assets/scss/app.scss
  templates/home/_club.html.twig
  templates/home/index.html.twig
Labels: Changes requested

#29 Fix_US02_Footer
  assets/scss/app.scss
  templates/_footer.html.twig
  templates/home/index.html.twig
Labels: Corrections done, Reviewed by PO

#18 Section Partenaires
  assets/images/logo-intersport.jpg
  assets/images/logo-nemo.jpg
  assets/images/logo-veloland.png
  assets/scss/app.scss
  composer.json
  composer.lock
  config/bundles.php
  src/Controller/HomeController.php
  src/DataFixtures/AppFixtures.php
  src/Entity/Sponsor.php
  src/Repository/SponsorRepository.php
  symfony.lock
  templates/_sponsors.html.twig
  templates/home/index.html.twig
Labels: Corrections done, Reviewed by PO

#26 Sprint01 us07 accueil trail
  assets/images/GTB-Blanc@2x.png
  assets/images/GTB-Test-VMA-2.jpg
  assets/images/GTriB-base-blanc@2x.png
  assets/images/WP_20170924_09_49_02_Rich.jpg
  assets/images/WP_20170924_11_25_07_Rich.jpg
  assets/images/WP_20170924_12_16_46_Rich.jpg
  assets/scss/app.scss
  src/Entity/Association.php
  src/Repository/AssociationRepository.php
  templates/home/_trail.html.twig
  templates/home/index.html.twig
Labels: Reviewed by PO

#52 Sprint02 us08 accueil section triathlon
  assets/images/GTB-14.jpg
  assets/scss/app.scss
  src/Controller/HomeController.php
  src/DataFixtures/AppFixtures.php
  templates/home/_trail.html.twig
  templates/home/_triathlon.html.twig
  templates/home/index.html.twig
Labels: Corrections done, Reviewed by PO

#53 Sprint02 us63 page login
  assets/scss/_vars.scss
  assets/scss/app.scss
  composer.json
  composer.lock
  config/packages/security.yaml
  config/routes.yaml
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthentificatorAuthenticator.php
  templates/_navbar.html.twig
  templates/security/login.html.twig
  templates/user/index.html.twig
Labels: Corrections done, Reviewed by PO

#54 fix récupération avec l'entité
  src/Controller/HomeController.php
Labels: Reviewed by PO

#55 Changement Scss
  assets/scss/app.scss
Labels: Reviewed by PO

#58 fix scss
  assets/scss/_vars.scss
  assets/scss/app.scss
Labels: Reviewed by PO

#61 Sprint01 us04 accueil evenements
  assets/scss/app.scss
  src/Controller/HomeController.php
  src/DataFixtures/AppFixtures.php
  src/Entity/Event.php
  src/Repository/EventRepository.php
  templates/home/_events.html.twig
  templates/home/_trail.html.twig
  templates/home/index.html.twig
Labels: Changes requested

#64 fix done
  assets/images/GTriB-Blanc@0.5x.png
  assets/scss/app.scss
  templates/home/_trail.html.twig
  templates/home/_triathlon.html.twig
Labels: PO needs holliday, Reviewed by PO

#67 Sprint03 us45 page trail texte
  assets/scss/app.scss
  src/Controller/TrailController.php
  templates/trail/index.html.twig
Labels: Reviewed by PO

#66 création et ajout des fichiers entity/galery galeryRepository et _Hom…
  assets/scss/app.scss
  src/Controller/HomeController.php
  src/DataFixtures/AppFixtures.php
  src/Entity/Galery.php
  src/Repository/GaleryRepository.php
  templates/home/_HomeGalery.html.twig
  templates/home/index.html.twig
Labels: Reviewed by PO

#71 Us10 admin tableau bord
  assets/js/app.js
  assets/scss/admin.scss
  assets/scss/app.scss
  src/Controller/AdminController.php
  templates/admin/_header.html.twig
  templates/admin/_navbar.html.twig
  templates/admin/index.html.twig
  templates/baseAdmin.html.twig
Labels: Reviewed by PO

#72 Fix navbar#1
  assets/js/app.js
  assets/js/main.js
  assets/scss/app.scss
  package.json
  yarn.lock
Labels: Reviewed by PO

#75 created 1 fixture file for each entity
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/AssociationFixtures.php
  src/DataFixtures/EventFixtures.php
Labels: PO is POtato, Reviewed by PO

#78 fix done
  assets/scss/admin.scss
  assets/scss/app.scss
  templates/_footer.html.twig
Labels: PO is POtato, Reviewed by PO

#79 Dev to Master
  assets/images/GTriB-Blanc@0.5x.png
  assets/js/app.js
  assets/js/main.js
  assets/scss/admin.scss
  assets/scss/app.scss
  package.json
  src/Controller/AdminController.php
  src/Controller/HomeController.php
  src/Controller/TrailController.php
  src/Controller/TriathlonController.php
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/AssociationFixtures.php
  src/DataFixtures/EventFixtures.php
  src/Entity/Event.php
  src/Entity/Galery.php
  src/Repository/EventRepository.php
  src/Repository/GaleryRepository.php
  templates/_footer.html.twig
  templates/_navbar.html.twig
  templates/admin/_header.html.twig
  templates/admin/_navbar.html.twig
  templates/admin/index.html.twig
  templates/baseAdmin.html.twig
  templates/home/_HomeGalery.html.twig
  templates/home/_events.html.twig
  templates/home/_trail.html.twig
  templates/home/_triathlon.html.twig
  templates/home/index.html.twig
  templates/trail/index.html.twig
  templates/triathlon/index.html.twig
  yarn.lock
Labels: Reviewed by PO

#83 Fix15298
  assets/scss/app.scss
  src/DataFixtures/GalleryFixtures.php
  templates/admin/_header.html.twig
  templates/home/_trail.html.twig
  templates/home/_triathlon.html.twig
Labels: Reviewed by PO

#80 Us10 admin tableau bord - Backend
  assets/scss/admin.scss
  assets/scss/app.scss
  phpstan.neon
  src/Controller/AdminController.php
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/CommentFixtures.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Comment.php
  src/Entity/Event.php
  src/Entity/User.php
  src/Repository/CommentRepository.php
  src/Repository/EventRepository.php
  templates/admin/_cardEventsIndex.html.twig
  templates/admin/_header.html.twig
  templates/admin/_navbar.html.twig
  templates/admin/index.html.twig
Labels: Reviewed by PO

#86 Update GalleryFixtures.php
  src/DataFixtures/GalleryFixtures.php
Labels: PO needs holiday, Reviewed by PO, Reviewed by PO suppléant

#84 Dev to master
  assets/scss/admin.scss
  assets/scss/app.scss
  phpstan.neon
  src/Controller/AdminController.php
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/CommentFixtures.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/GalleryFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Comment.php
  src/Entity/Event.php
  src/Entity/User.php
  src/Repository/CommentRepository.php
  src/Repository/EventRepository.php
  templates/admin/_cardEventsIndex.html.twig
  templates/admin/_header.html.twig
  templates/admin/_navbar.html.twig
  templates/admin/index.html.twig
  templates/home/_trail.html.twig
  templates/home/_triathlon.html.twig
Labels: Reviewed by PO

#87 us done
  assets/scss/admin.scss
  src/Controller/AdminEventController.php
  src/Controller/HomeController.php
  src/Entity/Event.php
  src/Form/EventType.php
  templates/admin/_navbar.html.twig
  templates/event/_delete_form.html.twig
  templates/event/_form.html.twig
  templates/event/edit.html.twig
  templates/event/index.html.twig
  templates/event/new.html.twig
Labels: Reviewed by PO

#96 correction gestion des events vide
  templates/home/_events.html.twig
Labels: PO is POtato, PO needs holiday, Reviewed by PO suppléant

#97 Us14 admin ajout partenaires
  .gitignore
  assets/js/main.js
  assets/scss/admin.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  public/uploads/.gitignore
  src/Controller/AdminPageHomeController.php
  src/DataFixtures/AppFixtures.php
  src/Entity/Sponsor.php
  src/Form/SponsorType.php
  symfony.lock
  templates/_sponsors.html.twig
  templates/admin/_navbar.html.twig
  templates/admin/page_home.html.twig
Labels: Reviewed by PO
