Repository WildCodeSchool/orleans-0219-php-gtb, pull requests merged in 2019-07, with the labels that each got.

#101 Us15 admin suppression partenaire
  assets/js/main.js
  assets/scss/admin.scss
  public/uploads/images/sponsors/logo_intersport.png
  src/Controller/AdminPageHomeController.php
  src/DataFixtures/AppFixtures.php
  templates/admin/page_home.html.twig
Labels: PO is POtato, PO needs holiday, Reviewed by PO

#89 Sprint01 us05 accueil formulaire
  assets/scss/app.scss
  composer.json
  composer.lock
  config/services.yaml
  src/Controller/ContactController.php
  src/Entity/Contact.php
  src/Form/ContactType.php
  src/Repository/ContactRepository.php
  templates/contact/email.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
Labels: PO is POtato, PO needs holiday, Reviewed by PO

#98 Sprint03 us37 admin asso
  .travis.yml
  assets/fonts/FontAwesome.otf
  assets/js/app.js
  assets/js/main.js
  assets/scss/admin.scss
  assets/scss/app.scss
  assets/scss/editAssociation.scss
  package.json
  src/Controller/AdminAssociationController.php
  src/DataFixtures/AppFixtures.php
  src/Form/Association1Type.php
  src/Form/AssociationType.php
  templates/admin/_navbar.html.twig
  templates/admin/index.html.twig
  templates/association/_delete_form.html.twig
  templates/association/_form.html.twig
  templates/association/edit.html.twig
  templates/association/index.html.twig
  templates/association/show.html.twig
  templates/base.html.twig
  templates/home/_trail.html.twig
  templates/home/_triathlon.html.twig
  templates/trail/index.html.twig
  templates/triathlon/index.html.twig
  travis.php.ini
  webpack.config.js
  yarn.lock
Labels: PO is POtato, PO needs holiday, Reviewed by PO

#116 Fix Navbar
  templates/admin/_navbar.html.twig
Labels: PO is POtato, PO needs holiday, Reviewed by PO

#113 Us53 coureur
  assets/scss/app.scss
  src/Controller/MemberController.php
  src/DataFixtures/EventFixtures.php
  src/Entity/Event.php
  templates/member/event_to_come.html.twig
Labels: Reviewed by PO

#123 Sprint 05 us 65 page club
  src/Controller/ClubController.php
  templates/_navbar.html.twig
  templates/club/index.html.twig
Labels: Reviewed by PO suppléant

#122 fix scss done
  assets/images/header-site-gtb.jpg
  assets/scss/app.scss
  src/DataFixtures/AppFixtures.php
  templates/_footer.html.twig
  templates/_navbar.html.twig
  templates/_sponsors.html.twig
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/home/_events.html.twig
  templates/home/_jumbotron.html.twig
  templates/home/_trail.html.twig
  templates/home/_triathlon.html.twig
  templates/home/index.html.twig
Labels: Reviewed by PO

#121 Show one event to come by Id
  assets/scss/app.scss
  src/Controller/MemberController.php
  src/DataFixtures/AppFixtures.php
  src/Entity/Comment.php
  src/Entity/Sponsor.php
  templates/member/event_to_come.html.twig
  templates/member/show_event_to_come.html.twig
Labels: Reviewed by PO

#99 création d'un nouveau membre
  assets/scss/app.scss
  composer.lock
  config/packages/twig.yaml
  config/packages/vich_uploader.yaml
  src/Controller/UserController.php
  src/DataFixtures/GenderFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Activity.php
  src/Entity/Gender.php
  src/Entity/User.php
  src/Form/UserType.php
  src/Repository/ActivityRepository.php
  src/Repository/GenderRepository.php
  symfony.lock
  templates/security/login.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
Labels: Corrections done, PO is POtato

#125 Sprint05 us03 galerie publique
  src/Controller/GaleryController.php
  templates/_sponsors.html.twig
  templates/galery/index.html.twig
  templates/home/_events.html.twig
Labels: PO is POtato, PO needs holiday, Reviewed by PO

#126 Sprint05 us51 galerie membre
  src/Controller/MemberController.php
  templates/private_galery/index.html.twig
Labels: PO is POtato, PO needs holiday, Reviewed by PO

#127 Fix lah
  assets/js/app.js
  assets/js/main.js
  assets/scss/admin.scss
  assets/scss/app.scss
  config/packages/vich_uploader.yaml
  public/uploads/images/sponsors/logo_intersport.png
  src/Form/SponsorType.php
  templates/_navbar.html.twig
  templates/admin/_navbar.html.twig
  templates/admin/index.html.twig
  templates/admin/page_home.html.twig
  webpack.config.js
Labels: PO is POtato, PO needs holiday, Reviewed by PO

#134 Fix membercreate
  src/Controller/UserController.php
  src/Entity/User.php
  templates/user/_form.html.twig
Labels: Reviewed by PO

#135 Admin showing all gallery images
  config/packages/vich_uploader.yaml
  src/Controller/AdminGalleryController.php
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/GalleryFixtures.php
  templates/admin/_navbar.html.twig
  templates/admin/galery.html.twig
Labels: PO is POtato, PO needs holiday, Reviewed by PO suppléant

#136 Sprint 05 crud commentaires
  assets/scss/admin.scss
  src/Controller/AdminCommentController.php
  src/DataFixtures/CommentFixtures.php
  src/Entity/Comment.php
  src/Form/CommentModerationType.php
  src/Form/CommentType.php
  templates/admin/_navbar.html.twig
  templates/comment/_delete_form.html.twig
  templates/comment/_form.html.twig
  templates/comment/edit.html.twig
  templates/comment/index.html.twig
  templates/comment/new.html.twig
  templates/comment/show.html.twig
Labels: Reviewed by PO, Reviewed by Sauron

#138 Sprint05 us58 page perso
  assets/scss/_vars.scss
  assets/scss/app.scss
  src/Controller/MemberController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/UserType.php
  src/Security/LoginFormAuthentificatorAuthenticator.php
  templates/member_page/index.html.twig
  templates/user/edit.html.twig
Labels: Corrections done, Kill me plz, PO is POtato, Reviewed by PO

#139 Fix crud commentaires
  src/Entity/Comment.php
Labels: Kill me plz, PO is POtato, PO needs holiday, Reviewed by PO, Reviewed by Sauron

#141 Us28 admin gallery add
  config/packages/vich_uploader.yaml
  src/Controller/AdminGalleryController.php
  src/DataFixtures/GalleryFixtures.php
  src/Entity/Galery.php
  src/Form/GalleryType.php
  src/Form/MemberCommentType.php
  templates/admin/gallery.html.twig
Labels: Reviewed by PO

#143 Sprint05 us70 legal mentions
  assets/scss/app.scss
  src/Controller/LegalMentionController.php
  templates/_footer.html.twig
  templates/legal_mention/index.html.twig
Labels: Reviewed by PO

#144 Fix link
  templates/home/_HomeGalery.html.twig
Labels: Reviewed by PO

#145 Deleting image gallery
  src/Controller/AdminGalleryController.php
  templates/admin/gallery.html.twig
Labels: Reviewed by PO

#147 Sprint 05 admin user
  config/services.yaml
  src/Controller/AdminUserController.php
  src/Form/AdminUserType.php
  src/Form/CommentModerationType.php
  templates/admin/_navbar.html.twig
  templates/user/_delete_form.html.twig
  templates/user/editAdmin.html.twig
  templates/user/index.html.twig
Labels: Reviewed by PO

#148 Us55 coureur event
  assets/scss/app.scss
  config/packages/vich_uploader.yaml
  src/Controller/AdminPageHomeController.php
  src/Controller/GaleryController.php
  src/Controller/MemberController.php
  src/Entity/Comment.php
  src/Form/MemberCommentType.php
  templates/admin/gallery.html.twig
  templates/home/_HomeGalery.html.twig
  templates/member/show_event_to_come.html.twig
Labels: Reviewed by PO

#149 Sprint05 roles admin
  src/Entity/User.php
  src/Form/AdminUserType.php
  templates/home/_HomeGalery.html.twig
  templates/user/editAdmin.html.twig
Labels: Reviewed by PO

#152 Fix pics even
  assets/scss/admin.scss
  config/packages/vich_uploader.yaml
  src/DataFixtures/EventFixtures.php
  src/Entity/Event.php
  src/Form/EventType.php
  src/Repository/EventRepository.php
  templates/admin/index.html.twig
  templates/event/_form.html.twig
  templates/event/index.html.twig
  templates/home/_HomeGalery.html.twig
  templates/home/_events.html.twig
  templates/member/event_to_come.html.twig
  templates/member/show_event_to_come.html.twig
Labels: Reviewed by PO

#154 Fixing isprivate button
  src/Form/GalleryType.php
  templates/admin/gallery.html.twig
  templates/admin/page_home.html.twig
  templates/association/_delete_form.html.twig
  templates/comment/_delete_form.html.twig
  templates/event/_delete_form.html.twig
  templates/user/_delete_form.html.twig
Labels: Reviewed by PO

#155 changement du label gender en français dans le fichier GenderFixtures
  src/Controller/MemberController.php
  src/DataFixtures/GenderFixtures.php
  src/Security/LoginFormAuthentificatorAuthenticator.php
Labels: Reviewed by PO

#146 Sprint05 us66 password reset
  assets/scss/app.scss
  config/services.yaml
  src/Controller/SecurityController.php
  src/Form/ChangePasswordFormType.php
  src/Form/ForgottenPasswordType.php
  src/Service/TokenService.php
  templates/security/changePassword.html.twig
  templates/security/login.html.twig
  templates/security/resetPassword.html.twig
Labels: Corrections done

#156 correction de l'indentation dans le fichier services.yaml
  config/services.yaml
Labels: Reviewed by PO

#158 responsivité du jumbotron
  assets/scss/app.scss
  src/Entity/User.php
  templates/home/_jumbotron.html.twig
Labels: Reviewed by PO

#159 ajout titres aux sections evenement et galerie
  templates/home/_HomeGalery.html.twig
  templates/home/_events.html.twig
Labels: Reviewed by PO suppléant

#153 ajout des liens de la member page vers les events et la galerie
  templates/galery/index.html.twig
  templates/home/_HomeGalery.html.twig
  templates/member_page/index.html.twig
Labels: Corrections done

#157 titles and font fixed
  assets/fonts/Pop Warner.ttf
  assets/scss/_vars.scss
  assets/scss/app.scss
  config/services.yaml
Labels: Corrections done, Reviewed by PO suppléant

#160 Fix refonte footer
  assets/scss/app.scss
  templates/_footer.html.twig
Labels: Reviewed by PO suppléant

#161 Fix summernote
  assets/scss/editAssociation.scss
  src/Form/Association1Type.php
Labels: Reviewed by PO

#150 Sprint05 us78925 trombi
  assets/scss/app.scss
  src/Controller/ClubController.php
  src/Controller/TrombinoscopeController.php
  src/Repository/UserRepository.php
  src/Services/MembersGetting.php
  templates/club/index.html.twig
  templates/trombinoscope/index.html.twig
Labels: Reviewed by PO

#163 ajout de la navbar et footer sur les pages login et forgotten passwor…
  assets/scss/app.scss
  src/Controller/HomeController.php
  templates/_navbar.html.twig
  templates/security/login.html.twig
  templates/security/resetPassword.html.twig
Labels: Reviewed by PO

#162 fix done
  templates/base.html.twig
Labels: Changes requested

#166 ajout du bouton vers de trombi depuis la m=page member et modif des b…
  assets/scss/app.scss
  templates/member_page/index.html.twig
Labels: Reviewed by PO

#165 changement du btn de soumission de com et texttype en textareatype
  src/Form/MemberCommentType.php
  templates/member/show_event_to_come.html.twig
Labels: Reviewed by PO suppléant

#167 font + size changed on labels
  assets/scss/editAssociation.scss
Labels: Reviewed by PO suppléant

#168 fix done
  assets/scss/app.scss
Labels: Reviewed by PO

#169 à la recherche du add perdu
  assets/scss/app.scss
  src/Form/EventType.php
  templates/admin/gallery.html.twig
  templates/admin/page_home.html.twig
  templates/association/_delete_form.html.twig
  templates/association/_form.html.twig
  templates/association/edit.html.twig
  templates/base.html.twig
  templates/comment/_delete_form.html.twig
  templates/comment/index.html.twig
  templates/comment/show.html.twig
  templates/contact/index.html.twig
  templates/event/_delete_form.html.twig
  templates/event/_form.html.twig
  templates/event/edit.html.twig
  templates/event/index.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/editAdmin.html.twig
  templates/user/index.html.twig
Labels: Reviewed by PO suppléant

#171 Fix sponsor carousel
  assets/images/arrow.png
  assets/images/play.png
  assets/images/stop.png
  assets/js/app.js
  assets/js/home.js
  assets/js/main.js
  assets/scss/app.scss
  config/services.yaml
  package.json
  templates/_sponsors.html.twig
  templates/admin/gallery.html.twig
  templates/home/index.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed by PO suppléant

#173 Fix jumbotitre
  assets/scss/app.scss
  templates/home/_HomeGalery.html.twig
  templates/home/_club.html.twig
  templates/home/_events.html.twig
Labels: Reviewed by PO suppléant

#174 config env pour swiftmailer
  .env
Labels: Reviewed by PO

#170 ajout du userReposository dans les controller modifiés car présence d…
  assets/scss/app.scss
  src/Controller/ClubController.php
  src/Controller/GaleryController.php
  src/Controller/HomeController.php
  src/Controller/MemberController.php
  src/Controller/TrailController.php
  src/Controller/TriathlonController.php
  src/Controller/TrombinoscopeController.php
  templates/_footer.html.twig
  templates/_navbar.html.twig
  templates/galery/index.html.twig
  templates/member_page/index.html.twig
  templates/private_galery/index.html.twig
Labels: Reviewed by PO

#175 Fix event to come
  assets/scss/app.scss
  templates/member/event_to_come.html.twig
  templates/member/show_event_to_come.html.twig
Labels: Reviewed by PO suppléant

#177 creation de l'admin avec migration generate
  src/Migrations/Version20190709084835.php
Labels: Reviewed by PO suppléant

#181 rectification des erreurs en cas de bdd vide pour la table association
  templates/club/index.html.twig
  templates/home/_club.html.twig
  templates/home/_trail.html.twig
  templates/home/_triathlon.html.twig
  templates/trail/index.html.twig
  templates/triathlon/index.html.twig
Labels: Review Requested

#179 remplissage bdd pour les activités
  src/Migrations/Version20190709084835.php
Labels: Review Requested

#183 Creation activity
  src/Migrations/Version20190709084835.php
Labels: Reviewed by PO suppléant

#180 Fix securisation routes
  config/packages/security.yaml
  src/Controller/AdminAssociationController.php
  src/Controller/AdminCommentController.php
  src/Controller/AdminController.php
  src/Controller/AdminEventController.php
  src/Controller/AdminGalleryController.php
  src/Controller/AdminPageHomeController.php
  src/Controller/AdminUserController.php
  src/Controller/MemberController.php
  src/Migrations/Version20190709084835.php
  templates/_navbar.html.twig
Labels: Reviewed by PO suppléant

#185 Fix maybe the last
  assets/scss/_vars.scss
  assets/scss/app.scss
  templates/contact/index.html.twig
  templates/home/index.html.twig
Labels: Corrections done

#186 Fix design home
  assets/images/logo_veloland.jpg
  assets/scss/admin.scss
  assets/scss/app.scss
  src/Form/ContactType.php
  templates/_footer.html.twig
  templates/contact/index.html.twig
  templates/galery/index.html.twig
  templates/home/_HomeGalery.html.twig
  templates/home/_events.html.twig
  templates/home/_trail.html.twig
  templates/home/_triathlon.html.twig
Labels: Conflicts solved

#187 Dev
  assets/images/logo_veloland.jpg
  assets/scss/_vars.scss
  assets/scss/admin.scss
  assets/scss/app.scss
  src/Form/ContactType.php
  templates/_footer.html.twig
  templates/contact/index.html.twig
  templates/galery/index.html.twig
  templates/home/_HomeGalery.html.twig
  templates/home/_events.html.twig
  templates/home/_trail.html.twig
  templates/home/_triathlon.html.twig
  templates/home/index.html.twig
Labels: Reviewed by PO

#190 Reparation merge
  assets/scss/app.scss
  templates/contact/index.html.twig
  templates/home/_club.html.twig
Labels: Reviewed by PO

#191 Dev
  assets/scss/app.scss
  templates/contact/index.html.twig
  templates/home/_club.html.twig
Labels: Reviewed by PO

#192 Fix display gallery member gallery
  assets/scss/app.scss
  templates/private_galery/index.html.twig
Labels: Reviewed by PO suppléant

#193 Fix again
  assets/scss/admin.scss
  assets/scss/app.scss
  src/Entity/Event.php
  src/Form/EventType.php
  templates/_footer.html.twig
  templates/admin/_header.html.twig
  templates/club/index.html.twig
  templates/event/_form.html.twig
  templates/event/new.html.twig
  templates/home/_club.html.twig
  templates/home/_events.html.twig
  templates/home/_trail.html.twig
  templates/home/_triathlon.html.twig
  templates/member_page/index.html.twig
  templates/security/login.html.twig
  templates/trail/index.html.twig
  templates/triathlon/index.html.twig
Labels: Reviewed by PO

#195 Fix again and again
  assets/scss/app.scss
  src/Controller/SecurityController.php
  src/Controller/UserController.php
  templates/base.html.twig
Labels: Reviewed by PO

#196 Fix Office members redirection
  assets/js/main.js
  assets/scss/admin.scss
  composer.json
  src/Controller/AdminPageHomeController.php
  src/Controller/SecurityController.php
  src/Security/LoginFormAuthentificatorAuthenticator.php
  templates/admin/gallery.html.twig
  templates/admin/page_home.html.twig
Labels: Reviewed by PO suppléant

#194 Fix events
  templates/home/_events.html.twig
Labels: Conflicts solved, Reviewed by PO

#198 Fix image event on homepage and display wysiwyg
  assets/scss/app.scss
  templates/club/index.html.twig
  templates/home/_club.html.twig
  templates/home/_trail.html.twig
  templates/home/_triathlon.html.twig
  templates/trail/index.html.twig
  templates/triathlon/index.html.twig
Labels: Reviewed by PO suppléant

#199 Fix button carousel
  assets/js/main.js
Labels: Reviewed by PO suppléant

#201 Fix trombi
  config/packages/security.yaml
  src/Controller/AdminUserController.php
  src/Controller/TrombinoscopeController.php
  src/Controller/UserController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/AdminUserType.php
  src/Repository/UserRepository.php
  src/Services/MembersGetting.php
  templates/trombinoscope/index.html.twig
  templates/user/editAdmin.html.twig
  templates/user/index.html.twig
Labels: Reviewed by PO suppléant

#202 Fix button size
  assets/scss/app.scss
Labels: Reviewed by PO suppléant

#203 Oh, la belle Dev
  assets/js/main.js
  assets/scss/admin.scss
  assets/scss/app.scss
  composer.json
  config/packages/security.yaml
  src/Controller/AdminPageHomeController.php
  src/Controller/AdminUserController.php
  src/Controller/SecurityController.php
  src/Controller/TrombinoscopeController.php
  src/Controller/UserController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Event.php
  src/Entity/User.php
  src/Form/AdminUserType.php
  src/Form/EventType.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthentificatorAuthenticator.php
  src/Services/MembersGetting.php
  templates/_footer.html.twig
  templates/admin/_header.html.twig
  templates/admin/gallery.html.twig
  templates/admin/page_home.html.twig
  templates/base.html.twig
  templates/club/index.html.twig
  templates/event/_form.html.twig
  templates/event/new.html.twig
  templates/home/_club.html.twig
  templates/home/_events.html.twig
  templates/home/_trail.html.twig
  templates/home/_triathlon.html.twig
  templates/home/index.html.twig
  templates/member/event_to_come.html.twig
  templates/member_page/index.html.twig
  templates/private_galery/index.html.twig
  templates/security/changePassword.html.twig
  templates/security/login.html.twig
  templates/security/resetPassword.html.twig
  templates/trail/index.html.twig
  templates/triathlon/index.html.twig
  templates/trombinoscope/index.html.twig
  templates/user/edit.html.twig
  templates/user/editAdmin.html.twig
  templates/user/index.html.twig
Labels: Reviewed by PO suppléant

#218 changement couleurs sections
  assets/scss/app.scss
Labels: Reviewed by PO

#219 modification de la font-size de la balise p, mise en majuscule des h1…
  assets/scss/app.scss
  templates/_footer.html.twig
  templates/club/index.html.twig
  templates/member_page/index.html.twig
  templates/security/changePassword.html.twig
  templates/security/login.html.twig
  templates/security/resetPassword.html.twig
  templates/trail/index.html.twig
  templates/triathlon/index.html.twig
  templates/user/edit.html.twig
  templates/user/new.html.twig
Labels: Reviewed by PO suppléant

#221 modification du readme afin de configurer correctement le .env pour l…
  .env
  README.md
Labels: Review Requested

#224 Navbar jumbotron
  assets/scss/app.scss
  templates/_navbar.html.twig
Labels: Reviewed by PO

#227 Navbar jumbotron
  assets/scss/app.scss
  templates/home/_events.html.twig
Labels: Reviewed by PO

#240 encadrants sportifs fixés
  config/packages/security.yaml
  src/Controller/TrombinoscopeController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
Labels: Corrections done, Reviewed by PO

#244 Fix the last last last last help
  src/Controller/AdminUserController.php
  src/Entity/User.php
Labels: Review Requested

#245 ajout d'un unique entity pour le field email dans l'entity user
  src/Entity/User.php
Labels: Review Requested

#250 changement du nom du webmaster et de son adresse mail au passage
  templates/legal_mention/index.html.twig
Labels: Review Requested, fix
